import type { Metadata } from "next";
import { Container, Nav, Navbar, NavLink } from "react-bootstrap";

import '../styles/app.scss';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <body>
                <Container fluid="xl">
                    <header>
                        <Navbar>
                            <NavLink href="/">Home</NavLink>
                            <NavLink href="/transactions">Transactions</NavLink>
                        </Navbar>
                    </header>

                    <main className="mt-4">
                        {children}
                    </main>
                </Container>
            </body>
        </html>
    );
}
